name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
      - name: 💡 Coding habits and activity - Mildly interesting facts
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Europe/Amsterdam
          output_action: none
          delay: 120
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: >-
          🌸 Anilist watch list and reading list - Favorites anime and currently
          watching
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
          plugin_anilist_user: WICK3DCHA0S
          output_action: none
          delay: 120
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}